### ISSUE TITLE
Do not know score sometimes

### ISSUE THREAD

**Issue by Abjo5441** [ogghead/Moon_Boersma_Coe_CSCI2270_FinalProject#34]
If you choose to take another card while playing, there are times when the program just says if you won or lost, but never tells you your score. A simple cout statement saying the users score might be nice for the user here, even if it isn't crucial to the game.  Other than that it's a really cool project!

**Comment by RichardWasTaken** [comment]
I put in a total money remaining Cout before the player bets, hopefully that was what you meant by score. Thanks.
